### ISSUE TITLE
PSR support

### ISSUE THREAD

**Issue by JoshuaBehrens** [avolutions/avolutions#164]
Hi, I stumbled upon this framework and looked into it. Are there any thoughts on providing implementations for PSR? This would add lots of compatibility e.g. for requests, logging or caching.

**Comment by AlxndrVgt** [comment]
Hey @JoshuaBehrens, 
Yes it is planned to add PSR support, at least for container (PSR-11), logging (PSR-3) and maybe HTTP message interface (PSR-7).

In our next release (0.9.0-alpha) we will introduce a Dependency Injection Container based on PSR-11 (see branch "feature-145-dependency-injection").

**Comment by JoshuaBehrens** [comment]
Thanks for the answer. I will come back later when I see more PSR :)
